global using Dating.Profile.CommandService.API;
global using Dating.Shared.API.Controllers;
global using Dating.Shared.Application.SQRS;
global using Marten;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using Dating.Shared.API.Middleware;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc.Authorization;